project:
  type: website

website:
  title: "Ikechukwu Ofodile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: events.qmd
        text: Conferences
      - href: blog.qmd
        text: Blog

  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: GitHub
        url: https://github.com/ic-ofodile-bristol
      - icon: linkedin
        text: LinkedIn
        url: YOUR-LINKEDIN-URL
      - icon: envelope
        text: Email
        url: mailto:ic.ofodile@bristol.ac.uk
      - text: "Google Scholar"
        url: YOUR-GOOGLE-SCHOLAR-URL
      - text: PrO-AI CDT
        url: https://www.bristol.ac.uk/cdt/practice-oriented-ai/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
