project:
  type: website

website:
  title: "Ikechukwu Ofodile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      

  sidebar:
    style: "docked"
    logo: "./images/profile_pic.JPG"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: GitHub
        url: https://github.com/ic-ofodile-bristol
      - text: "ic.ofodile@bristol.ac.uk"
        icon: envelope
        href: "mailto:ic.ofodile@bristol.ac.uk"
      - text: "Google Scholar"
        icon: mortarboard
        href: "https://scholar.google.com/citations?user=NEaNvBgAAAAJ&hl=en&oi=ao"
      - text: "ORCID - 0000-0002-1980-2850"
        icon: person-badge
        href: "https://orcid.org/0000-0002-1980-2850"
        target: "_blank"
      - text: PrO-AI CDT
        url: https://www.bristol.ac.uk/cdt/practice-oriented-ai/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
